Add support for fs.FS file system support
bloeys/assimp-go pull request #3
Opened 2024-12-12 07:25 UTC by Bradbev

Adds support for asig.ImportFileEx, which accepts an fs.FS.  This allows asig to load from go fs implementations.

2024-12-12 07:50 UTC, bloeys commented
Hey @Bradbev,

This looks awesome!

Ill try to test this weekend and if all is good it would be a cool addition.

Thanks for the contribution :D

2025-03-27 17:56 UTC, bloeys requested changes
Thanks @Bradbev for the PR, I think this is very useful, but just have a couple small concerns before merging.

2025-03-27 17:56 UTC, bloeys commented on asig/asig.go
> -#cgo darwin,arm64 LDFLAGS: -l assimp_darwin_arm64
Hey @Bradbev  am just worried about this change.
We ship libs and link to them, the original `assimp_darwin_armd64`, but now this links to what exactly?

2025-03-27 17:56 UTC, bloeys commented on asig/asig.go
> +	wrapper.Pin(cio)
Where does this get unpinned?

2025-03-28 06:27 UTC, Bradbev commented on asig/asig.go
> -#cgo darwin,arm64 LDFLAGS: -l assimp_darwin_arm64
I had forgotten about this error.  I'm on an M2 Mac, Darwin Kernel Version 24.3.0.  When running against head I get the following error 
```
 ~/d/f/assimp-go ((v0.4.4))> go run main.go 
# command-line-arguments
ld: warning: ignoring duplicate libraries: '-lassimp_darwin_arm64'
dyld[31900]: Library not loaded: @rpath/libassimp.5.dylib
  Referenced from: <819A0E7A-372E-BAC5-EAC4-9326ACEBB23D> /private/var/folders/53/vddczdhx5877862m4p7gfh3m0000gn/T/go-build147998708/b001/exe/main
  Reason: no LC_RPATH's found
signal: abort trap
```
Is the Mac build running?  I'll see if I can work around that issue, but any help would be great.

2025-03-28 06:32 UTC, Bradbev commented on asig/asig.go
> +	wrapper.Pin(cio)
wrapper.Pin gets called on 268 and also every time a file is opened.  My understanding is Pinner should be used when exposing Go memory to C.  Unpin is called in the defer on line 261, so all the pins are released when this func exits.

2025-03-28 07:36 UTC, Bradbev commented on asig/asig.go
> -#cgo darwin,arm64 LDFLAGS: -l assimp_darwin_arm64
Hmm, I must have followed the install instructions at https://github.com/bloeys/assimp-go?tab=readme-ov-file#installing-on-macos .  But I'm not actually sure how the original cgo LDFLAGS worked.
Anyway, after copying the dylib as per link above, the -rpath directive seems to be needed so that /usr/local/lib is actually searched.  I suspect this is security related for OSX.

2025-03-28 13:18 UTC, bloeys commented on asig/asig.go
> +	wrapper.Pin(cio)
Oh yeah unpin removes all pins not just one :D

2025-03-28 13:20 UTC, bloeys commented on asig/asig.go
> -#cgo darwin,arm64 LDFLAGS: -l assimp_darwin_arm64
Hmm I see, could be.

I unfortunately no longer have a mac, but if it works for you how about we merge then and also ensure the build works.

Thanks for the help here, its trying to debug this without a mac 😅

2025-03-29 04:15 UTC, Bradbev commented on asig/asig.go
> -#cgo darwin,arm64 LDFLAGS: -l assimp_darwin_arm64
Conflict should be resolved now.

2025-03-29 14:38 UTC, bloeys commented
Thanks Bradbev, highly appreciated. Lets merge and hope all goes well for Mac people!

2025-03-29 14:38 UTC, merged